"""v2_schema - catalog/event/snapshot Kern-Datenmodell

Revision ID: 0002_v2_schema
Revises: 0001_baseline
Create Date: 2026-09-07
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_v2_schema'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), server_default='MdCategory', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'name', name='uq_category_catalog_name')
    )
    op.create_index(op.f('ix_category_catalog_id'), 'category', ['catalog_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_catalog_id'), 'event', ['catalog_id'], unique=False)
    op.create_index('uq_event_single_active', 'event', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('active_order',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deposit_return_unit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_return_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_day', sa.Date(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('deposit_return_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_business_day'), 'bill', ['business_day'], unique=False)
    op.create_index(op.f('ix_bill_event_id'), 'bill', ['event_id'], unique=False)
    op.create_table('day_close',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('business_day', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'business_day')
    )
    op.create_table('stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_item_catalog_id'), 'stock_item', ['catalog_id'], unique=False)
    op.create_table('deposit_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_return_event_id'), 'deposit_return', ['event_id'], unique=False)
    op.create_table('item_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bill_steps', sa.Numeric(precision=10, scale=3), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_variant_stock_item_id'), 'item_variant', ['stock_item_id'], unique=False)
    op.create_table('active_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('item_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['active_order.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_variant_id'], ['item_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'item_variant_id', name='uq_active_line_variant')
    )
    op.create_index(op.f('ix_active_order_line_event_id'), 'active_order_line', ['event_id'], unique=False)
    op.create_table('bill_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_variant_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('variant_name', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_per_unit', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_variant_id'], ['item_variant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_item_bill_id'), 'bill_item', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_item_bill_id'), table_name='bill_item')
    op.drop_table('bill_item')
    op.drop_index(op.f('ix_active_order_line_event_id'), table_name='active_order_line')
    op.drop_table('active_order_line')
    op.drop_index(op.f('ix_item_variant_stock_item_id'), table_name='item_variant')
    op.drop_table('item_variant')
    op.drop_index(op.f('ix_deposit_return_event_id'), table_name='deposit_return')
    op.drop_table('deposit_return')
    op.drop_index(op.f('ix_stock_item_catalog_id'), table_name='stock_item')
    op.drop_table('stock_item')
    op.drop_table('day_close')
    op.drop_index(op.f('ix_bill_event_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_business_day'), table_name='bill')
    op.drop_table('bill')
    op.drop_table('active_order')
    op.drop_index('uq_event_single_active', table_name='event', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_event_catalog_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_category_catalog_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('catalog')
    # ### end Alembic commands ###
